version: "3.4"

services:
   postgresql:
           image: postgres:10.10
           restart: "no"
           environment:
                   POSTGRES_DB: db
                   POSTGRES_USER: admin
                   POSTGRES_PASSWORD: password
           volumes:
                   - .:/app
                   - postgres_db:/var/lib/postgresql/data

           networks:
                   - backend
   app:
           image: projet:projet
           restart: "no"
           command: python3 app.py
           volumes:
                   - .:/app
           ports:
                   - "5000:5000"
           networks:
                   - backend
volumes:
  postgres_db:
networks:
  backend:

